apiVersion: v1
kind: Service
metadata:
  name: techtrends-service
  labels:
    app: techtrends
spec:
  selector:
    app: techtrends
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
